### ISSUE TITLE
Node js version problems

### ISSUE THREAD

**Issue by likegeo** [patrickjquinn/P-Brain.ai#73]
P-Brain not working with nodejs v12.14.0, it will be an update soon? so we can continue working the project with latest features... many thanks!

`C:\WorkSpace\brain>yarn start
yarn run v1.16.0
warning package.json: License should be a valid SPDX license expression
$ node server.js
Using default SQLite database provider
Setting up database.
Error: Cannot find module 'C:\WorkSpace\brain\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node'
Require stack:
- C:\WorkSpace\brain\node_modules\sqlite3\lib\sqlite3.js
- C:\WorkSpace\brain\db\sqlite_db\index.js
- C:\WorkSpace\brain\db\index.js
- C:\WorkSpace\brain\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\WorkSpace\brain\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\WorkSpace\\brain\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\WorkSpace\\brain\\db\\sqlite_db\\index.js',
    'C:\\WorkSpace\\brain\\db\\index.js',
    'C:\\WorkSpace\\brain\\server.js'
  ]
}
(node:92036) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\WorkSpace\brain\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node'
Require stack:
- C:\WorkSpace\brain\node_modules\sqlite3\lib\sqlite3.js
- C:\WorkSpace\brain\db\sqlite_db\index.js
- C:\WorkSpace\brain\db\index.js
- C:\WorkSpace\brain\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\WorkSpace\brain\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
(node:92036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:92036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.00s.`

**Comment by Ashish117** [comment]
@likegeo Actually It's the problem with sqlite 3 installation. You can google search the search.

**Comment by patrickjquinn** [comment]
You might need to update your sqllite node package in the project directory, I dont work with this much but will look into maintaining it a little further. I'm curious, what are people using this project for personally? Any cool examples of where it's being used?

**Comment by likegeo** [comment]
@Ashish117 Already searched but nothing about this issue. If i downgrade to node v6.xx is working but no on v12.xx. Also i have installed the latest mysql 3 -->> same problem.

Thank you,

**Comment by Ashish117** [comment]
@likegeo Try Uninstalling sqlite3 from global dir and reinstall the one in the project dir, Or you should try another way as the error points to only sqlite3

**Comment by likegeo** [comment]
@patrickjquinn It is for personal usage yes, i work on a personal assistant to control some devices on my home and also for fun with my litle boy :) it is realy a good work and i want thank you for this :) it ill be realy cool if you continue to update and make it bether than is it ;)

**Comment by likegeo** [comment]
@Ashish117 Thank you, i will try this.

**Comment by likegeo** [comment]
# @Ashish117 same problem, uninstall from global dir and reinstall on the project dir, same error. As i see sqlite3 is not supported by latest node js version. My question is how to use another database driver  ... that can replace the sqlite3. May be mango database...or another one... and if yes can somebody help me to integrate with?

Thank you very much for help!

**Comment by patrickjquinn** [comment]
Try the latest commit and let us know if it works for you.

**Comment by likegeo** [comment]
@patrickjquinn You are the best!!! Working perfect! Thank you very much :)
